################################################################################
# TP53 Mutation Status Classification for CPTAC Datasets
#
# Description:
#   Classify TP53 mutation status (TP53mut vs TP53wt) and functional categories
#   (GOF, LOF, DN, VUS) across six CPTAC datasets.
#
# Methodology:
#   Based on Shahbandi et al. (2023) Cell Death Discovery
#   "Homogenous TP53mut-associated tumor biology across mutation types"
#   DOI: 10.1038/s41420-023-01413-1
#
# Data sources:
#   - FunctionDownload_r21.csv: TP53 Database R21 functional annotation
#   - MutationView_r21.csv: TP53 Database R21 mutation overview (for DN backup)
#   - *_somatic_mutation.maf: CPTAC MAF-format mutation data from linkedomicskb
#
# Author: Generated by Antigravity AI assistant
# Date: 2026-04-20
################################################################################

# ==============================================================================
# Section 1: Setup and Library Loading
# ==============================================================================

library(dplyr)
library(readr)
library(openxlsx)
library(tidyr)
library(stringr)

# Define base path
base_path <- "C:/Users/danny/Documents/R_project/linkedomicskb_TP53_GOF"

# Define datasets and cancer types
cancer_types <- c("BRCA", "CCRCC", "COAD", "GBM", "HNSCC", "LSCC", "LUAD", "OV", "PDAC", "UCEC")
datasets <- data.frame(
  folder = cancer_types,
  cancer_type = cancer_types,
  stringsAsFactors = FALSE
)

# Define hotspot mutations
hotspot_list <- c("R175H", "R273C", "R273H", "R248Q", "R248W",
                  "R282W", "Y220C", "G245S", "H179R", "V157F")

# Define TP53mut variant classifications
tp53mut_variants <- c("Missense_Mutation", "Nonsense_Mutation", "Splice_Site",
                      "Translation_Start_Site", "Nonstop_Mutation",
                      "Frame_Shift_Del", "Frame_Shift_Ins",
                      "In_Frame_Del", "In_Frame_Ins", "Unknown")

# Define truncating variant types (subset of tp53mut)
truncating_variants <- c("Nonsense_Mutation", "Frame_Shift_Del", "Frame_Shift_Ins",
                         "Splice_Site", "Translation_Start_Site", "Nonstop_Mutation")

# Create output directory
output_dir <- file.path(base_path, "TP53_mutation_classification")
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

cat("=== TP53 Mutation Classification Pipeline ===\n")
cat("Output directory:", output_dir, "\n\n")

# ==============================================================================
# Section 2: Build GOF/LOF/DN Annotation from FunctionDownload_r21.csv
# ==============================================================================

cat("Loading FunctionDownload_r21.csv...\n")

func_db <- read.csv(file.path(base_path, "FunctionDownload_r21.csv"),
                    stringsAsFactors = FALSE)

cat("  Total entries in FunctionDownload:", nrow(func_db), "\n")
cat("  Columns:", paste(colnames(func_db), collapse = ", "), "\n\n")

# For each unique AAchange, determine GOF/LOF/DN status
# by aggregating across all entries (multiple experiments per mutation)

func_annotation <- func_db %>%
  # Filter to single amino acid changes (not compound mutations with "/")
  filter(!grepl("/", AAchange),
         AAchange != "",
         !is.na(AAchange)) %>%
  group_by(AAchange) %>%
  summarise(
    # GOF: any entry with Gain_of_Function that is non-empty, non-NA,
    # and does NOT start with "No"
    has_GOF = any(
      !is.na(Gain_of_Function) &
      Gain_of_Function != "" &
      Gain_of_Function != "NA" &
      !grepl("^No\\b", Gain_of_Function)
    ),
    # LOF: any entry with Loss_of_Function that is non-empty, non-NA
    has_LOF = any(
      !is.na(Loss_of_Function) &
      Loss_of_Function != "" &
      Loss_of_Function != "NA"
    ),
    # DN: any entry with Dominant_Negative_Activity starting with "Yes"
    has_DN = any(
      !is.na(Dominant_Negative_Activity) &
      grepl("^Yes", Dominant_Negative_Activity)
    ),
    .groups = "drop"
  ) %>%
  mutate(
    # Apply classification rules per paper:
    # If both GOF and LOF -> classify as GOF
    GOF = ifelse(has_GOF, 1L, 0L),
    LOF = ifelse(has_LOF & !has_GOF, 1L, 0L),
    DN  = ifelse(has_DN, 1L, 0L),
    non_DN = ifelse(has_DN, 0L, 1L)
  )

cat("GOF/LOF/DN annotation summary from FunctionDownload_r21.csv:\n")
cat("  Total unique AAchange entries:", nrow(func_annotation), "\n")
cat("  GOF mutations:", sum(func_annotation$GOF == 1), "\n")
cat("  LOF mutations:", sum(func_annotation$LOF == 1), "\n")
cat("  DN mutations:", sum(func_annotation$DN == 1), "\n")
cat("  Neither GOF nor LOF (in DB but no clear evidence):",
    sum(func_annotation$GOF == 0 & func_annotation$LOF == 0), "\n\n")

# Also load MutationView for DN backup lookup (DNEclass column)
cat("Loading MutationView_r21.csv for supplementary DN annotation...\n")
mv_db <- read.csv(file.path(base_path, "MutationView_r21.csv"),
                  stringsAsFactors = FALSE)

# Extract DN info from MutationView as backup
mv_dn_annotation <- mv_db %>%
  filter(!is.na(AAchange), AAchange != "") %>%
  group_by(AAchange) %>%
  summarise(
    mv_has_DN = any(
      !is.na(DNEclass) &
      DNEclass %in% c("Yes", "Moderate")
    ),
    .groups = "drop"
  )

cat("  MutationView DN annotations:", sum(mv_dn_annotation$mv_has_DN), "mutations\n\n")

# ==============================================================================
# Section 3: Classification Functions
# ==============================================================================

#' Classify a single TP53 mutation
#'
#' @param protein_change aaChange from MAF (e.g., "p.R175H")
#' @param variant_class Variant_Classification from MAF
#' @param func_anno Data frame with FunctionDownload annotations
#' @param mv_dn Data frame with MutationView DN annotations
#' @return Named list with GOF, LOF, DN, non_DN, category
classify_tp53_mutation <- function(protein_change, variant_class,
                                   func_anno, mv_dn) {
  result <- list(GOF = 0L, LOF = 0L, DN = 0L, non_DN = 0L, category = "VUS")

  # Extract AAchange from aaChange (remove "p." prefix)
  aa_change <- gsub("^p\\.", "", protein_change)

  # Handle frameshift notation: e.g., "E204Sfs*43" -> look up without fs part
  # These are truncating and should be LOF anyway
  is_truncating <- variant_class %in% truncating_variants || grepl("\\*|fs", protein_change, ignore.case = TRUE)

  # Step 1: Look up in FunctionDownload annotation
  match_idx <- which(func_anno$AAchange == aa_change)

  if (length(match_idx) > 0) {
    row <- func_anno[match_idx[1], ]
    result$GOF <- row$GOF
    result$LOF <- row$LOF
    result$DN  <- row$DN
    result$non_DN <- row$non_DN

    if (result$GOF == 1) {
      result$category <- "GOF"
    } else if (result$LOF == 1) {
      result$category <- "LOF"
    } else {
      # In database but no clear GOF or LOF evidence
      # If truncating -> LOF; else VUS
      if (is_truncating) {
        result$LOF <- 1L
        result$category <- "LOF"
        result$non_DN <- 1L
      } else {
        result$category <- "VUS"
      }
    }
  } else {
    # Step 2: Not found in FunctionDownload
    # Check MutationView for DN info
    mv_match <- which(mv_dn$AAchange == aa_change)
    if (length(mv_match) > 0 && mv_dn$mv_has_DN[mv_match[1]]) {
      result$DN <- 1L
      result$non_DN <- 0L
    }

    if (is_truncating) {
      # Truncating mutations -> LOF
      result$LOF <- 1L
      result$category <- "LOF"
      result$DN <- 0L
      result$non_DN <- 1L
    } else {
      # Non-truncating, not in database -> VUS
      result$category <- "VUS"
    }
  }

  # Ensure DN/non_DN consistency for TP53mut
  if (result$GOF == 1 || result$LOF == 1) {
    if (result$DN == 0) {
      result$non_DN <- 1L
    }
  }

  return(result)
}

# ==============================================================================
# Section 4: Main Processing Loop
# ==============================================================================

all_results <- list()

for (i in seq_len(nrow(datasets))) {
  ds_folder <- datasets$folder[i]
  ds_cancer <- datasets$cancer_type[i]

  cat("Processing dataset:", ds_folder, "(", ds_cancer, ")\n")

  # --- Read mutation file ---
  mut_file <- file.path(base_path, ds_folder, paste0(ds_cancer, "_somatic_mutation.maf"))
  
  # Read mutation file, skipping comment lines automatically
  mut_df <- read.delim(mut_file, comment.char = "#", stringsAsFactors = FALSE, sep = "\t")
  
  # Extract all unique samples from the mutation file
  all_samples <- unique(mut_df$Tumor_Sample_Barcode)
  cat("  Total samples (from MAF):", length(all_samples), "\n")

  # --- Filter for TP53 mutations ---
  tp53_muts <- mut_df %>%
    filter(Hugo_Symbol == "TP53") %>%
    select(Tumor_Sample_Barcode, Variant_Classification, aaChange) %>%
    distinct()

  cat("  TP53 mutation entries:", nrow(tp53_muts), "\n")

  # --- Classify each sample ---
  sample_results <- data.frame(
    sample_id = character(),
    cancer_type = character(),
    protein_change = character(),
    variant_classification = character(),
    wt = integer(),
    mt = integer(),
    LOF = integer(),
    GOF = integer(),
    DN = integer(),
    non_DN = integer(),
    hotspot = integer(),
    category = character(),
    stringsAsFactors = FALSE
  )

  for (sample in all_samples) {
    # Get TP53 mutations for this sample
    sample_tp53 <- tp53_muts %>%
      filter(Tumor_Sample_Barcode == sample)

    if (nrow(sample_tp53) == 0) {
      # No TP53 mutations -> TP53wt
      sample_results <- rbind(sample_results, data.frame(
        sample_id = sample,
        cancer_type = ds_cancer,
        protein_change = "[Not Available]",
        variant_classification = NA_character_,
        wt = 1L, mt = 0L,
        LOF = 0L, GOF = 0L, DN = 0L, non_DN = 0L,
        hotspot = 0L,
        category = "TP53wt",
        stringsAsFactors = FALSE
      ))
      next
    }

    # Check for TP53mut-type variants
    mut_type_rows <- sample_tp53 %>%
      filter(Variant_Classification %in% tp53mut_variants)

    if (nrow(mut_type_rows) == 0) {
      # Has TP53 entries but only synonymous/intronic/UTR -> TP53wt
      # Use the first protein change for reference
      pc <- sample_tp53$aaChange[1]
      if (is.na(pc) || pc == "" || pc == ".") pc <- "[Not Available]"
      sample_results <- rbind(sample_results, data.frame(
        sample_id = sample,
        cancer_type = ds_cancer,
        protein_change = pc,
        variant_classification = sample_tp53$Variant_Classification[1],
        wt = 1L, mt = 0L,
        LOF = 0L, GOF = 0L, DN = 0L, non_DN = 0L,
        hotspot = 0L,
        category = "TP53wt",
        stringsAsFactors = FALSE
      ))
      next
    }

    # TP53mut: classify each mutation and select the most impactful
    classified_muts <- list()
    for (j in seq_len(nrow(mut_type_rows))) {
      pc <- mut_type_rows$aaChange[j]
      vc <- mut_type_rows$Variant_Classification[j]

      if (is.na(pc) || pc == "" || pc == ".") {
        # No protein change available, classify by variant type
        if (vc %in% truncating_variants) {
          cls <- list(GOF = 0L, LOF = 1L, DN = 0L, non_DN = 1L, category = "LOF")
        } else {
          cls <- list(GOF = 0L, LOF = 0L, DN = 0L, non_DN = 0L, category = "VUS")
        }
      } else {
        cls <- classify_tp53_mutation(pc, vc, func_annotation, mv_dn_annotation)
      }

      classified_muts[[j]] <- list(
        protein_change = ifelse(is.na(pc) || pc == "" || pc == ".", "[Not Available]", pc),
        variant_classification = vc,
        GOF = cls$GOF, LOF = cls$LOF,
        DN = cls$DN, non_DN = cls$non_DN,
        category = cls$category
      )
    }

    # Priority: GOF > LOF > VUS
    priority_order <- c("GOF" = 1, "LOF" = 2, "VUS" = 3)
    best_idx <- 1
    best_priority <- priority_order[classified_muts[[1]]$category]
    if (is.na(best_priority)) best_priority <- 99

    if (length(classified_muts) > 1) {
      for (k in 2:length(classified_muts)) {
        k_priority <- priority_order[classified_muts[[k]]$category]
        if (is.na(k_priority)) k_priority <- 99
        if (k_priority < best_priority) {
          best_idx <- k
          best_priority <- k_priority
        }
      }
    }

    best <- classified_muts[[best_idx]]

    # Determine hotspot status
    aa_for_hotspot <- gsub("^p\\.", "", best$protein_change)
    is_hotspot <- ifelse(aa_for_hotspot %in% hotspot_list, 1L, 0L)

    sample_results <- rbind(sample_results, data.frame(
      sample_id = sample,
      cancer_type = ds_cancer,
      protein_change = best$protein_change,
      variant_classification = best$variant_classification,
      wt = 0L, mt = 1L,
      LOF = best$LOF, GOF = best$GOF,
      DN = best$DN, non_DN = best$non_DN,
      hotspot = is_hotspot,
      category = best$category,
      stringsAsFactors = FALSE
    ))
  }

  # Summary for this dataset
  n_total <- nrow(sample_results)
  n_wt <- sum(sample_results$wt == 1)
  n_mt <- sum(sample_results$mt == 1)
  n_gof <- sum(sample_results$GOF == 1)
  n_lof <- sum(sample_results$LOF == 1)
  n_dn <- sum(sample_results$DN == 1)
  n_vus <- sum(sample_results$category == "VUS")
  n_hotspot <- sum(sample_results$hotspot == 1)

  cat("  Results: Total=", n_total,
      " TP53wt=", n_wt, "(", round(n_wt/n_total*100, 1), "%)",
      " TP53mut=", n_mt, "(", round(n_mt/n_total*100, 1), "%)",
      " GOF=", n_gof, " LOF=", n_lof, " DN=", n_dn,
      " VUS=", n_vus, " Hotspot=", n_hotspot, "\n\n")

  # Save individual dataset CSV
  output_file <- file.path(output_dir,
                           paste0(ds_folder, "_TP53_classification.csv"))
  write.csv(sample_results, output_file, row.names = FALSE)

  all_results[[ds_folder]] <- sample_results
}

# ==============================================================================
# Section 5: Combined Output
# ==============================================================================

cat("Generating combined output files...\n")

# Combine all datasets
combined_results <- bind_rows(all_results)

# Save combined CSV
combined_csv <- file.path(output_dir, "all_CPTAC_TP53_classification.csv")
write.csv(combined_results, combined_csv, row.names = FALSE)
cat("  Combined CSV saved:", combined_csv, "\n")

# Save combined XLSX (matching reference table format)
# Format: sample_id, cancer_type, protein_change, wt, mt, LOF, GOF, DN, non-DN
xlsx_data <- combined_results %>%
  select(sample_id, cancer_type, protein_change,
         wt, mt, LOF, GOF, DN, `non_DN`) %>%
  rename(`non-DN` = non_DN)

xlsx_file <- file.path(output_dir, "all_CPTAC_TP53_classification.xlsx")
wb <- createWorkbook()
addWorksheet(wb, "TP53_Classification")
writeData(wb, "TP53_Classification", xlsx_data)

# Apply formatting
header_style <- createStyle(
  textDecoration = "bold",
  halign = "center",
  border = "bottom",
  fgFill = "#4472C4",
  fontColour = "white"
)
addStyle(wb, "TP53_Classification", header_style,
         rows = 1, cols = 1:ncol(xlsx_data), gridExpand = TRUE)

# Auto-width columns
setColWidths(wb, "TP53_Classification",
             cols = 1:ncol(xlsx_data), widths = "auto")

saveWorkbook(wb, xlsx_file, overwrite = TRUE)
cat("  Combined XLSX saved:", xlsx_file, "\n")

# ==============================================================================
# Section 6: Summary Statistics
# ==============================================================================

cat("\nGenerating summary statistics...\n")

summary_stats <- combined_results %>%
  group_by(cancer_type) %>%
  summarise(
    dataset = first(cancer_type),
    total_samples = n(),
    TP53wt_count = sum(wt == 1),
    TP53wt_pct = round(sum(wt == 1) / n() * 100, 1),
    TP53mut_count = sum(mt == 1),
    TP53mut_pct = round(sum(mt == 1) / n() * 100, 1),
    GOF_count = sum(GOF == 1),
    GOF_pct = round(sum(GOF == 1) / n() * 100, 1),
    LOF_count = sum(LOF == 1),
    LOF_pct = round(sum(LOF == 1) / n() * 100, 1),
    DN_count = sum(DN == 1),
    DN_pct = round(sum(DN == 1) / n() * 100, 1),
    nonDN_count = sum(non_DN == 1 & mt == 1),
    nonDN_pct = round(sum(non_DN == 1 & mt == 1) / n() * 100, 1),
    VUS_count = sum(category == "VUS"),
    VUS_pct = round(sum(category == "VUS") / n() * 100, 1),
    hotspot_count = sum(hotspot == 1),
    hotspot_pct = round(sum(hotspot == 1) / n() * 100, 1),
    .groups = "drop"
  ) %>%
  select(-dataset)

# Add a total row
total_row <- combined_results %>%
  summarise(
    cancer_type = "TOTAL",
    total_samples = n(),
    TP53wt_count = sum(wt == 1),
    TP53wt_pct = round(sum(wt == 1) / n() * 100, 1),
    TP53mut_count = sum(mt == 1),
    TP53mut_pct = round(sum(mt == 1) / n() * 100, 1),
    GOF_count = sum(GOF == 1),
    GOF_pct = round(sum(GOF == 1) / n() * 100, 1),
    LOF_count = sum(LOF == 1),
    LOF_pct = round(sum(LOF == 1) / n() * 100, 1),
    DN_count = sum(DN == 1),
    DN_pct = round(sum(DN == 1) / n() * 100, 1),
    nonDN_count = sum(non_DN == 1 & mt == 1),
    nonDN_pct = round(sum(non_DN == 1 & mt == 1) / n() * 100, 1),
    VUS_count = sum(category == "VUS"),
    VUS_pct = round(sum(category == "VUS") / n() * 100, 1),
    hotspot_count = sum(hotspot == 1),
    hotspot_pct = round(sum(hotspot == 1) / n() * 100, 1)
  )

summary_stats <- bind_rows(summary_stats, total_row)

# Save summary CSV
summary_csv <- file.path(output_dir, "TP53_classification_summary.csv")
write.csv(summary_stats, summary_csv, row.names = FALSE)
cat("  Summary CSV saved:", summary_csv, "\n")

# Save summary XLSX with formatting
wb2 <- createWorkbook()
addWorksheet(wb2, "Summary")
writeData(wb2, "Summary", summary_stats)

addStyle(wb2, "Summary", header_style,
         rows = 1, cols = 1:ncol(summary_stats), gridExpand = TRUE)

# Highlight total row
total_style <- createStyle(textDecoration = "bold", fgFill = "#E2EFDA")
addStyle(wb2, "Summary", total_style,
         rows = nrow(summary_stats) + 1,
         cols = 1:ncol(summary_stats), gridExpand = TRUE)

setColWidths(wb2, "Summary", cols = 1:ncol(summary_stats), widths = "auto")
saveWorkbook(wb2, file.path(output_dir, "TP53_classification_summary.xlsx"),
             overwrite = TRUE)

# Print summary table to console
cat("\n")
cat("=== TP53 Classification Summary ===\n\n")
print(as.data.frame(summary_stats), row.names = FALSE)

# ==============================================================================
# Section 7: Detailed Mutation Report
# ==============================================================================

cat("\n\nGenerating detailed mutation report...\n")

# Count each unique protein change across all datasets
mutation_detail <- combined_results %>%
  filter(mt == 1) %>%
  group_by(protein_change) %>%
  summarise(
    n_samples = n(),
    datasets = paste(unique(cancer_type), collapse = ", "),
    GOF = first(GOF),
    LOF = first(LOF),
    DN = first(DN),
    category = first(category),
    is_hotspot = ifelse(gsub("^p\\.", "", first(protein_change)) %in% hotspot_list,
                        "Yes", "No"),
    .groups = "drop"
  ) %>%
  arrange(desc(n_samples))

mutation_detail_csv <- file.path(output_dir, "TP53_mutation_detail.csv")
write.csv(mutation_detail, mutation_detail_csv, row.names = FALSE)
cat("  Mutation detail CSV saved:", mutation_detail_csv, "\n")

cat("\nTop 20 most frequent TP53 mutations across CPTAC:\n")
print(head(as.data.frame(mutation_detail), 20), row.names = FALSE)

cat("\n=== Pipeline Complete ===\n")
cat("All output files saved to:", output_dir, "\n")
